package ca.toropov.microcad.fogPrettifier.util;

import ca.toropov.microcad.fogPrettifier.FogSummary;
import javafx.collections.ObservableList;
import org.simplejavamail.email.EmailBuilder;
import org.simplejavamail.email.EmailPopulatingBuilder;
import org.simplejavamail.mailer.Mailer;
import org.simplejavamail.mailer.MailerBuilder;
import org.simplejavamail.mailer.config.TransportStrategy;

import javax.activation.FileDataSource;
import java.io.File;
import java.util.List;

/**
 * Author: toropov
 * Date: 10/5/2018
 */
public class EmailSender {
    private static Mailer mailer;

    public static boolean send(FogSummary summary, String group, String po, List<String> emails) {
        if (mailer == null) {
            mailer = MailerBuilder
                    .withTransportStrategy(TransportStrategy.SMTP_TLS)
//                    .withSMTPServer() //Removed due to security reasons
                    .buildMailer();
        }

        ObservableList<FogSummary.Row> rows = summary.generateSummary();
        StringBuilder html = new StringBuilder("<h4>Group: " + group + "</h4>");
        if (!po.isEmpty()) {
            html.append("<h4>PO: ").append(po).append("</h4>");
        }
        html.append("<table style=\"font-family:arial, sans-serif;border-collapse:collapse;\"><tr>")
                .append("<th style=\"border:1px solid #dddddd;text-align:left;padding:8px;\">Model</th>")
                .append("<th style=\"border:1px solid #dddddd;text-align:left;padding:8px;\">Grade A</th>")
                .append("<th style=\"border:1px solid #dddddd;text-align:left;padding:8px;\">Grade B</th>")
                .append("<th style=\"border:1px solid #dddddd;text-align:left;padding:8px;\">Grade C</th>")
                .append("<th style=\"border:1px solid #dddddd;text-align:left;padding:8px;\">Total</th></tr>");
        for (FogSummary.Row row : rows) {
            html.append("<tr><td style=\"border:1px solid #dddddd;text-align:left;padding:8px;\">").append(row.getModel()).append("</td>");
            html.append("<td style=\"border:1px solid #dddddd;text-align:left;padding:8px;\">").append(row.getAGrades()).append("</td>");
            html.append("<td style=\"border:1px solid #dddddd;text-align:left;padding:8px;\">").append(row.getBGrades()).append("</td>");
            html.append("<td style=\"border:1px solid #dddddd;text-align:left;padding:8px;\">").append(row.getCGrades()).append("</td>");
            html.append("<td style=\"border:1px solid #dddddd;text-align:left;padding:8px;\">").append(row.getTotal()).append("</td></tr>");
        }
        html.append("</table><br></br><i>Automatically generated by Fog Prettifier</i>");

        EmailPopulatingBuilder email = EmailBuilder.startingBlank()
                .from("Fog Report", "NA")
                .withSubject(group + " - Incoming Fog Report")
                .withHTMLText(html.toString());

        File file = summary.saveFile(group + "_");
        if (file != null) {
            email.withAttachment(group + ".csv", new FileDataSource(file));
        }
        emails.forEach(email::to);

        try {
            mailer.sendMail(email.buildEmail());
            return true;
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }
}
