package ca.toropov.microcad.fogPrettifier;

import javafx.application.Application;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.image.Image;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.HBox;
import javafx.scene.paint.Color;
import javafx.scene.text.Font;
import javafx.scene.text.FontWeight;
import javafx.scene.text.Text;
import javafx.scene.text.TextAlignment;
import javafx.stage.FileChooser;
import javafx.stage.Stage;

import java.io.File;
import java.util.List;

/**
 * Author: toropov
 * Date: 9/28/2018
 */
public class Main extends Application {
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) {
        GridPane grid = new GridPane();
        grid.setAlignment(Pos.TOP_CENTER);
        grid.setHgap(10);
        grid.setVgap(10);
        grid.setPadding(new Insets(20, 20, 20, 20));

        FileChooser fileChooser = new FileChooser();
        fileChooser.setTitle("Select FOG generated report");
        fileChooser.getExtensionFilters().add(new FileChooser.ExtensionFilter("CSV files (*.csv)", "*.csv"));
        fileChooser.setInitialDirectory(new File(System.getProperty("user.home") + "/Downloads/"));

        Text infoText = new Text("  This program will prettify the inventory reports generated by FOG and save the files at the same folder by the name: \"fileName_pretty.csv\"");
        infoText.setFont(Font.font("Tahoma", FontWeight.NORMAL, 14));
        infoText.setWrappingWidth(250);
        infoText.setFill(Color.DIMGRAY);
        infoText.setTextAlignment(TextAlignment.JUSTIFY);
        grid.add(infoText, 0, 0, 2, 4);

        Text statusText = new Text();
        statusText.setFont(Font.font("Tahoma", FontWeight.BOLD, 12));
        statusText.setFill(Color.GRAY);
        statusText.setTextAlignment(TextAlignment.RIGHT);
        grid.add(statusText, 1, 7);

        Button btn = new Button("Choose files...");
        btn.setOnAction(event -> {
            statusText.setText("");
            List<File> file = fileChooser.showOpenMultipleDialog(primaryStage);
            if (file != null) {
                btn.setDisable(true);
                statusText.setText("Generating...");
                statusText.setFill(Color.GRAY);

                Prettifier.prettify(file, (response, color) -> {
                    btn.setDisable(false);
                    statusText.setText(response);
                    statusText.setFill(color);
                });
            }
        });
        HBox hBox = new HBox(btn);
        hBox.setAlignment(Pos.BOTTOM_CENTER);
        grid.add(hBox, 1, 5);

        primaryStage.setTitle("Fog Report Prettifier");
        primaryStage.getIcons().add(new Image(Main.class.getResourceAsStream("/icons/256.png")));
        primaryStage.setScene(new Scene(grid, 300, 200));
        primaryStage.setMinWidth(300);
        primaryStage.setMinHeight(200);
        primaryStage.show();
    }
}
